[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "term"
serifs = "sans"
no-cv-ss = true

  [buildPlans.iosevka-custom.variants]
  inherits = "ss09"

    [buildPlans.iosevka-custom.variants.design]
    at = "fourfold"
    cent = "open"
